{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "7e39cb35",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Accuracy: 0.9248554913294798\n",
      "Area Under ROC Curve: 0.9868387645874481\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from sklearn.ensemble import GradientBoostingClassifier\n",
    "from sklearn.metrics import accuracy_score, roc_auc_score\n",
    "\n",
    "# Load the training data from the first CSV file\n",
    "train_data = pd.read_csv(r\"C:\\Users\\KIIT\\Desktop\\Iterations\\iter2\\Combined_5.csv\")\n",
    "\n",
    "# Split the features and target variable\n",
    "X_train = train_data.drop('Facies', axis=1)\n",
    "y_train = train_data['Facies']\n",
    "\n",
    "# Load the test data from the unlabelled CSV file\n",
    "unlabelled_data = pd.read_csv(r\"C:\\Users\\KIIT\\Desktop\\las to csv\\SB-4.csv\")\n",
    "\n",
    "# Keep a copy of the unlabelled data\n",
    "labelled_data = unlabelled_data.copy()\n",
    "\n",
    "# Remove the 'Facies' column from the unlabelled data\n",
    "unlabelled_data.drop('Facies', axis=1, inplace=True)\n",
    "\n",
    "# Define the parameters for the gradient boosting classifier\n",
    "params = {\n",
    "    'n_estimators': 163,\n",
    "    'learning_rate': 0.016258128550853512,\n",
    "    'max_depth': 53,\n",
    "    'min_samples_split': 203,\n",
    "    'min_samples_leaf': 205,\n",
    "    'subsample': 0.9990808801724966\n",
    "}\n",
    "\n",
    "# Create a gradient boosting classifier object with the defined parameters\n",
    "gb_classifier = GradientBoostingClassifier(**params)\n",
    "\n",
    "# Train the classifier on the original training data\n",
    "gb_classifier.fit(X_train, y_train)\n",
    "\n",
    "# Load the test data from another CSV file\n",
    "test_data = pd.read_csv(r\"C:\\Users\\KIIT\\Desktop\\SB-10.csv\")\n",
    "\n",
    "# Split the features and target variable for the test data\n",
    "X_test = test_data.drop('Facies', axis=1)\n",
    "y_test = test_data['Facies']\n",
    "\n",
    "# Predict on the test set\n",
    "y_pred = gb_classifier.predict(X_test)\n",
    "\n",
    "# Calculate the accuracy of the classifier\n",
    "accuracy = accuracy_score(y_test, y_pred)\n",
    "\n",
    "# Print the accuracy\n",
    "print(\"Accuracy:\", accuracy)\n",
    "\n",
    "# Get predicted probabilities for the test data\n",
    "y_prob = gb_classifier.predict_proba(X_test)\n",
    "\n",
    "# Calculate the area under the ROC curve\n",
    "roc_auc = roc_auc_score(y_test, y_prob, multi_class='ovr')\n",
    "\n",
    "# Print the area under the ROC curve\n",
    "print(\"Area Under ROC Curve:\", roc_auc)\n",
    "\n",
    "# Use the trained classifier to predict labels for the unlabelled data\n",
    "predicted_labels = gb_classifier.predict(unlabelled_data)\n",
    "\n",
    "# Add the predicted labels to the labelled data\n",
    "labelled_data['Facies'] = predicted_labels\n",
    "\n",
    "# Store the labelled data in a new CSV file\n",
    "labelled_data.to_csv(r\"C:\\Users\\KIIT\\Desktop\\Iterations\\iter2\\L_SB-4.csv\", index=False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "44851a24",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CSV files combined successfully!\n"
     ]
    }
   ],
   "source": [
    "import csv\n",
    "import os\n",
    "\n",
    "# Path to the folder containing CSV files\n",
    "folder_path = r\"C:\\Users\\KIIT\\Desktop\\Iterations\\iter2\"\n",
    "\n",
    "\n",
    "# Get a list of all CSV files in the folder\n",
    "file_list = [file for file in os.listdir(folder_path) if file.endswith(\".csv\")]\n",
    "\n",
    "# Initialize a list to store the combined data\n",
    "combined_data = []\n",
    "\n",
    "# Iterate over each CSV file and append its data to the combined list\n",
    "for file in file_list:\n",
    "    file_path = os.path.join(folder_path, file)\n",
    "    with open(file_path, \"r\") as csvfile:\n",
    "        reader = csv.reader(csvfile)\n",
    "        header = next(reader)  # Read the header\n",
    "        for row in reader:\n",
    "            combined_data.append(row)\n",
    "\n",
    "# Path and filename for the combined CSV file\n",
    "combined_file_path = r\"C:\\Users\\KIIT\\Desktop\\Iterations\\iter2\\Combined_6.csv\"\n",
    "\n",
    "# Write the combined data to a new CSV file\n",
    "with open(combined_file_path, \"w\", newline=\"\") as csvfile:\n",
    "    writer = csv.writer(csvfile)\n",
    "    writer.writerow(header)  # Write the header\n",
    "    writer.writerows(combined_data)  # Write the data rows\n",
    "\n",
    "print(\"CSV files combined successfully!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "4ff56946",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Accuracy: 0.9263005780346821\n",
      "Confusion Matrix:\n",
      "[[503   1   2   1   8]\n",
      " [  5  38   0   3   2]\n",
      " [  0   0   8   1   0]\n",
      " [ 11   2   3  24   0]\n",
      " [ 12   0   0   0  68]]\n",
      "Area Under ROC Curve: 0.9876125222505031\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAqsAAAIhCAYAAABpMPNPAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8qNh9FAAAACXBIWXMAAA9hAAAPYQGoP6dpAABHwElEQVR4nO3dd3QUZeP28WsTUiCQAAm9iYQWQRKCaOhNpIgEeaSICEhRikrHgIgoEEBFQHoXpSqKqMCDFLEAEkqQzoNUNQgBDAIhQDLvH77kZ6SYyG7mJvv9nJNz2HtmZ69lzi4Xk3tmHJZlWQIAAAAM5GF3AAAAAOB2KKsAAAAwFmUVAAAAxqKsAgAAwFiUVQAAABiLsgoAAABjUVYBAABgLMoqAAAAjEVZBQAAgLEoqwCM9eOPP6pTp04qWbKkfH19lTNnTlWuXFljx47VuXPnXPraO3fuVO3atRUQECCHw6Hx48c7/TUcDodef/11p2/3n8ybN08Oh0MOh0Nff/31Tcsty1JwcLAcDofq1Knzr15jypQpmjdvXoae8/XXX982EwD3lc3uAABwKzNnzlSPHj1UtmxZDRgwQCEhIbp27Zq2bdumadOmafPmzfr0009d9vrPPfecLl26pMWLFytPnjy67777nP4amzdvVtGiRZ2+3fTKlSuXZs+efVMh3bhxo3766SflypXrX297ypQpCgoKUseOHdP9nMqVK2vz5s0KCQn5168LIOuhrAIwzubNm9W9e3c9+uijWr58uXx8fFKXPfroo+rXr59Wr17t0gx79uxR165d1bhxY5e9xiOPPOKybadH69attWDBAk2ePFn+/v6p47Nnz1ZERIQuXLiQKTmuXbsmh8Mhf39/2/9OAJiHaQAAjDNq1Cg5HA7NmDEjTVG9wdvbW0888UTq45SUFI0dO1blypWTj4+P8ufPr2effVY///xzmufVqVNHFSpUUExMjGrWrKkcOXLo/vvv1+jRo5WSkiLp/35Ffv36dU2dOjX11+WS9Prrr6f++a9uPOfYsWOpY+vXr1edOnUUGBio7Nmzq3jx4mrZsqUuX76cus6tpgHs2bNHzZs3V548eeTr66vQ0FC9//77ada58evyRYsWaciQISpcuLD8/f3VoEEDHTx4MH1/yZLatm0rSVq0aFHqWEJCgpYtW6bnnnvuls8ZPny4Hn74YeXNm1f+/v6qXLmyZs+eLcuyUte57777tHfvXm3cuDH17+/Gkekb2T/44AP169dPRYoUkY+Pjw4fPnzTNID4+HgVK1ZM1apV07Vr11K3v2/fPvn5+al9+/bpfq8A7l2UVQBGSU5O1vr16xUeHq5ixYql6zndu3fXoEGD9Oijj2rFihV68803tXr1alWrVk3x8fFp1j116pTatWunZ555RitWrFDjxo0VFRWlDz/8UJLUtGlTbd68WZL0n//8R5s3b059nF7Hjh1T06ZN5e3trTlz5mj16tUaPXq0/Pz8dPXq1ds+7+DBg6pWrZr27t2riRMn6pNPPlFISIg6duyosWPH3rT+4MGDdfz4cc2aNUszZszQ//73PzVr1kzJycnpyunv76///Oc/mjNnTurYokWL5OHhodatW9/2vT3//PNaunSpPvnkEz355JN68cUX9eabb6au8+mnn+r+++9XWFhY6t/f36dsREVF6cSJE5o2bZo+//xz5c+f/6bXCgoK0uLFixUTE6NBgwZJki5fvqynnnpKxYsX17Rp09L1PgHc4ywAMMipU6csSVabNm3Stf7+/fstSVaPHj3SjP/www+WJGvw4MGpY7Vr17YkWT/88EOadUNCQqzHHnsszZgkq2fPnmnGhg0bZt3qa3Pu3LmWJOvo0aOWZVnWxx9/bEmyYmNj75hdkjVs2LDUx23atLF8fHysEydOpFmvcePGVo4cOazff//dsizL2rBhgyXJatKkSZr1li5dakmyNm/efMfXvZE3JiYmdVt79uyxLMuyHnroIatjx46WZVnWAw88YNWuXfu220lOTrauXbtmvfHGG1ZgYKCVkpKSuux2z73xerVq1brtsg0bNqQZHzNmjCXJ+vTTT60OHTpY2bNnt3788cc7vkcAWQdHVgHc0zZs2CBJN53IU7VqVZUvX17r1q1LM16wYEFVrVo1zdiDDz6o48ePOy1TaGiovL291a1bN73//vs6cuRIup63fv161a9f/6Yjyh07dtTly5dvOsL716kQ0p/vQ1KG3kvt2rVVqlQpzZkzR7t371ZMTMxtpwDcyNigQQMFBATI09NTXl5eeu2113T27FmdPn063a/bsmXLdK87YMAANW3aVG3bttX777+v9957TxUrVkz38wHc2yirAIwSFBSkHDly6OjRo+la/+zZs5KkQoUK3bSscOHCqctvCAwMvGk9Hx8fJSYm/ou0t1aqVCmtXbtW+fPnV8+ePVWqVCmVKlVKEyZMuOPzzp49e9v3cWP5X/39vdyY35uR9+JwONSpUyd9+OGHmjZtmsqUKaOaNWvect2tW7eqYcOGkv68WsP333+vmJgYDRkyJMOve6v3eaeMHTt21JUrV1SwYEHmqgJuhrIKwCienp6qX7++tm/fftMJUrdyo7DFxcXdtOzXX39VUFCQ07L5+vpKkpKSktKM/31erCTVrFlTn3/+uRISErRlyxZFRESod+/eWrx48W23HxgYeNv3Icmp7+WvOnbsqPj4eE2bNk2dOnW67XqLFy+Wl5eXvvjiC7Vq1UrVqlVTlSpV/tVr3upEtduJi4tTz549FRoaqrNnz6p///7/6jUB3JsoqwCMExUVJcuy1LVr11uekHTt2jV9/vnnkqR69epJUuoJUjfExMRo//79ql+/vtNy3Tij/ccff0wzfiPLrXh6eurhhx/W5MmTJUk7duy47br169fX+vXrU8vpDfPnz1eOHDlcdlmnIkWKaMCAAWrWrJk6dOhw2/UcDoeyZcsmT0/P1LHExER98MEHN63rrKPVycnJatu2rRwOh1atWqXo6Gi99957+uSTT+562wDuDVxnFYBxIiIiNHXqVPXo0UPh4eHq3r27HnjgAV27dk07d+7UjBkzVKFCBTVr1kxly5ZVt27d9N5778nDw0ONGzfWsWPHNHToUBUrVkx9+vRxWq4mTZoob9686ty5s9544w1ly5ZN8+bN08mTJ9OsN23aNK1fv15NmzZV8eLFdeXKldQz7hs0aHDb7Q8bNkxffPGF6tatq9dee0158+bVggUL9OWXX2rs2LEKCAhw2nv5u9GjR//jOk2bNtW4ceP09NNPq1u3bjp79qzefvvtW15erGLFilq8eLGWLFmi+++/X76+vv9qnumwYcP07bffas2aNSpYsKD69eunjRs3qnPnzgoLC1PJkiUzvE0A9xbKKgAjde3aVVWrVtW7776rMWPG6NSpU/Ly8lKZMmX09NNPq1evXqnrTp06VaVKldLs2bM1efJkBQQEqFGjRoqOjr7lHNV/y9/fX6tXr1bv3r31zDPPKHfu3OrSpYsaN26sLl26pK4XGhqqNWvWaNiwYTp16pRy5sypChUqaMWKFalzPm+lbNmy2rRpkwYPHqyePXsqMTFR5cuX19y5czN0JyhXqVevnubMmaMxY8aoWbNmKlKkiLp27ar8+fOrc+fOadYdPny44uLi1LVrV/3xxx8qUaJEmuvQpsdXX32l6OhoDR06NM0R8nnz5iksLEytW7fWd999J29vb2e8PQCGcljWX67kDAAAABiEOasAAAAwFmUVAAAAxqKsAgAAwFiUVQAAABiLsgoAAABjUVYBAABgLMoqAAAAjJUlbwqQPazXP6+ELON8zCS7IyATcWVo9+Jw2J0AmSk5hQ+4O/HzTt8HnCOrAAAAMBZlFQAAAMairAIAAMBYlFUAAAAYi7IKAAAAY1FWAQAAYCzKKgAAAIxFWQUAAICxKKsAAAAwFmUVAAAAxqKsAgAAwFiUVQAAABiLsgoAAABjUVYBAABgLMoqAAAAjEVZBQAAgLEoqwAAADAWZRUAAADGoqwCAADAWJRVAAAAGIuyCgAAAGNRVgEAAGAsyioAAACMRVkFAACAsSirAAAAMBZlFQAAAMairAIAAMBYlFUAAAAYi7IKAAAAY1FWAQAAYCzKKgAAAIxFWQUAAICxKKsAAAAwFmUVAAAAxqKsAgAAwFiUVQAAABiLsgoAAABjUVYBAABgLMoqAAAAjEVZBQAAgLGy2R0Atzfk+SZ69YUmacZOxV9QyUcHp1mnc8vqyp0ru2L2HFfv6CXaf+RU6vL3hrRRvYfLqlC+AF1MTNKWXUf16oTPdOjYb5n2PuA827fFaN6c2dq/b4/OnDmjdydOVr36DeyOBReZPXO61q1do2NHj8jH11eVQsPUu09/3VfyfrujwQX4fLuX69eva/qUSVq18nOdjY9XUFA+NWveQl2e7y4PD44l/hV/G4bbe/hX3dcgKvXnoVajUpf169hALz1TV31GL1WNZ97Sb2cv6MtpLypnDp/UdXbuP6lur3+o0CdH6Ikek+VwOPTFlJ7y8HDY8XZwlxITL6ts2bJ6ZchrdkdBJti+batat22n+QuXatqMuUq+nqzu3Tor8fJlu6PBBfh8u5d5c2Zp2UeLNWjwUC377Eu93Le/5s+brcULP7Q7mnE4smq468kp+u3sH7dc1vPpuho7+7/6bP0uSVKXoR/o+LpRat24imYv+16SNOeT71PXPxF3TsMnf66YpYNVonCgjv4c7/o3AKeqUbO2atSsbXcMZJIp02eneTx8RLTq1YrQvn17FV7lIZtSwVX4fLuXH3ftVO269VWzVh1JUuEiRbV61Zfat3ePvcEMZOuR1Z9//llDhgxR3bp1Vb58eYWEhKhu3boaMmSITp48aWc0YwQXz6cja0Zq/xeva/7oTrqvSKAk6b4igSqUL0BrNx9IXffqtev6dvthPVLp1r8izOHrrWefeERHf47Xz6fOZ0p+AM5z8eKf/3ENCAiwOQmAuxUWFq6tP2zW8WNHJUmHDh5Q7I4dqlGzls3JzGPbkdXvvvtOjRs3VrFixdSwYUM1bNhQlmXp9OnTWr58ud577z2tWrVK1atXv+N2kpKSlJSUlGbMSkmWw8PTlfEzRcyeY+oy9AP97/hp5Q/MpVe6NNKGef0U/p+RKhjkL0k6fS7tUdfTZ/9Q8UJ504x1e6qmRvaOVM4cPjpw5JSadp+ka9eTM+19ALh7lmXpnbHRCqscruDSZeyOA+AudezcVRcv/qEnn2giT09PJScnq+dLvdWoyeN2RzOObWW1T58+6tKli959993bLu/du7diYmLuuJ3o6GgNHz48zZhngYfkVaiq07LaZc33+1L/vPew9MOuo9r7+et6ptnD2rr7z/+JWZaV5jkOx81ji1fFaN0PB1QwyF+9n22gD8c8p3qdxinp6nXXvwkAThE98g0dOnRI8+YvtDsKACdYs3qlVn7xuUaNeVv3lwrWwYMH9M6YUcqXL7+aNW9hdzyj2DYNYM+ePXrhhRduu/z555/Xnj3/PG8jKipKCQkJaX6yFQh3ZlRjXL5yVXsP/6pSxfPpVPwFSVKBQP806+TLm+umo60XLl7RTyfO6PsdP+np/rNUtmQBNa9XKdNyA7g7o0e9qY0b1mvWnPdVoGBBu+MAcILx77yljp276rHGTVW6TFk93qy52rXvqLmzZtgdzTi2ldVChQpp06ZNt12+efNmFSpU6B+34+PjI39//zQ/WWEKwK14e2VTuZIFdCo+Qcd+Oau4Mwmq/0i51OVe2TxVMzxYW3YdueN2HHLI24tz6wDTWZal6JFvaN3aNZox530VKVrM7kgAnOTKlcSbLlHl4emhFCvFpkTmsq2x9O/fXy+88IK2b9+uRx99VAUKFJDD4dCpU6f01VdfadasWRo/frxd8YwQ3aeFvvxmt07GnVf+vDk1qEsj5fLz1YLPf5AkTV64QQM6N9ThE6d1+MQZDez8mBKvXNOSVdsk/XkS1n8eC9e6zfsVf/6iCufPrX4dGygx6Zr++91eO98a/qXLly7pxIkTqY9/+flnHdi/XwEBASpUuLCNyeAKo0YM16qVX2j8xCny8/NTfPwZSVLOnLnk6+trczo4G59v91Krdl3NnjFNBQsVUqlSwTpwYL8+nD9PzSNb2h3NOA7r7xMcM9GSJUv07rvvavv27UpO/vOEH09PT4WHh6tv375q1arVv9pu9rBezoxpm/mjO6lG5WAF5vZT/PmL2rr7mIZP+UIH/nLR/xs3Bcjjn0Mxe46pd/RS7fspTpJUKF+Aprz2tMLKF1Me/xw6ffYPfbfjsEbNWKX/HT9t19tyuvMxk+yOkGlitv6gLp2evWn8ieYt9Oao0TYkynz2fWNlvtAKZW85PnxEtJpHPpnJaezhcKNLQvP5lpJT3OcDfunSRU2ZNFEb1q3V+XNnlS9ffj3WuKm6de8hLy9vu+NlCj/v9H3AbS2rN1y7dk3x8X9e8zMoKEheXl53tb2sUlaRPu5UVuFeZRXuVVbhXmUV6S+rRkxc9PLyStf8VAAAALgXbrcKAAAAY1FWAQAAYCzKKgAAAIxFWQUAAICxKKsAAAAwFmUVAAAAxqKsAgAAwFiUVQAAABiLsgoAAABjUVYBAABgLMoqAAAAjEVZBQAAgLEoqwAAADAWZRUAAADGoqwCAADAWJRVAAAAGIuyCgAAAGNRVgEAAGAsyioAAACMRVkFAACAsSirAAAAMBZlFQAAAMairAIAAMBYlFUAAAAYi7IKAAAAY1FWAQAAYCzKKgAAAIxFWQUAAICxKKsAAAAwFmUVAAAAxqKsAgAAwFiUVQAAABiLsgoAAABjUVYBAABgLMoqAAAAjEVZBQAAgLEoqwAAADAWZRUAAADGoqwCAADAWA7Lsiy7Qzjb5WtZ7i3hDv5IvG53BGSigBxedkdAJsp6/0IBuCF7Or/OObIKAAAAY1FWAQAAYCzKKgAAAIxFWQUAAICxKKsAAAAwFmUVAAAAxqKsAgAAwFiUVQAAABiLsgoAAABjUVYBAABgLMoqAAAAjEVZBQAAgLEoqwAAADAWZRUAAADGoqwCAADAWJRVAAAAGIuyCgAAAGNRVgEAAGAsyioAAACMRVkFAACAsSirAAAAMBZlFQAAAMairAIAAMBYlFUAAAAYi7IKAAAAY1FWAQAAYCzKKgAAAIxFWQUAAICxKKsAAAAwFmUVAAAAxqKsAgAAwFiUVQAAABiLsgoAAABjUVYBAABgLMoqAAAAjEVZBQAAgLEoqwAAADAWZRUAAADGoqwCAADAWJRVAAAAGCub3QFwd6ZNfk/Tp05OMxYYGKS1G7+zKRGcZfnHi7V82RKdivtVklTy/mB16PyCHqleU5J0+fJlTZ/0rr7buF4JCb+rYKHC+k/rdor8Txs7Y8MFlixaoHlzZyv+zBmVCi6tga8MVuXwKnbHgpMtXbxQHy1ZpF9//UWSVCq4tLq90EM1ata2ORlcYfbM6Vq3do2OHT0iH19fVQoNU+8+/XVfyfvtjmYcymoWUCq4tKbNmpP62MPD08Y0cJZ8+Qvq+V59VLRocUnS6i8/0+D+L2r2hx+rZKlgTRo3Rju3b9Wrb0SrYKEiitmySe+OHaHAfPlVs3Y9m9PDWVavWqmxo6M1ZOgwhYZV1sdLF6vH81316YovVahwYbvjwYkKFCyol/r0V/Hif37mV3y2XL1f7KnFH3+q4ODSNqeDs23ftlWt27bTAxUqKvl6siZNfFfdu3XWJ599qew5ctgdzygOy7Isu0M42+VrWe4t3da0ye9pw/p1WrJsud1RbPNH4nW7I2SapvWrqftL/fR485bq0DpS9R5tpA5dXkhd3qV9Kz1Sraa6dH/RxpSuFZDDy+4Imapdm6dUPiREr742PHUssllj1a3XQC/36WdjssyR9f6Fypha1aqqT78BatHyKbujwMXOnTunerUiNHvehwqv8pDdcTJF9nR+nTNnNQs4ceK4Hq1bU00fq69B/fvq55Mn7Y4EJ0tOTta6NSt1JTFRFSqGSpIqhobp+2826Mzp32RZlnZs26qTJ46pakR1e8PCaa5dvar9+/YqolqNNOMR1aprV+xOm1IhMyQnJ2v1yi+VmHhZD4aG2R0HmeDixT8kSQEBATYnMY/R0wBOnjypYcOGac6cObddJykpSUlJSWnGkj285ePj4+p4RqjwYCW9OWq0SpS4T2fPntWs6VPV8Zm2+vizz5U7dx674+Eu/XT4kHo8105Xr15V9uw5NOKtCbrv/lKSpJf7D9bYkcPUsml9eXpmk4eHQwNfHa4HQyvbnBrOcv7380pOTlZgYGCa8cDAIMXHn7EpFVzpf4cO6tl2bXT1apKy58ihcRMmq1SpYLtjwcUsy9I7Y6MVVjlcwaXL2B3HOEYfWT137pzef//9O64THR2tgICAND9vj4nOpIT2q1Gzlho8+phKlymrRyKq6b0p0yVJn3+23N5gcIriJUpq9oJlmjpngZq3bKVRrw/RsSM/SZI+Xvyh9u3+UdHvTNKsD5aoR+8BGjdmhLb9sNnm1HA2h8OR5rFlWTeNIWu4r2RJLVm2XPMXLFGrVm312pBB+umnw3bHgotFj3xDhw4d0uix4+yOYiRbj6yuWLHijsuPHDnyj9uIiopS375904wle3jfVa57WfYcORRcuoxOHD9udxQ4gZeXl4oW+/Nki3IhFXRg3159tPhDvdR3kGZOmaCRb01QRI0/zxQuVbqsDh86oMUfzlOVhyPsjA0nyZM7jzw9PRUfH59m/Ny5swoMDLIpFVzJy8tbxYuXkCQ9UKGi9u7drYUfztfQYW/YnAyuMnrUm9q4Yb3mvP+hChQsaHccI9laViMjI+VwOHSnc7z+6eiBj4/PTb/yd6cTrP7u6tWrOnr0J4WFh9sdBS5gWZauXb2q69ev6/r163I40v5yxMPDUylWik3p4Gxe3t4qH/KAtmz6XvUbPJo6vmXTJtWpV9/GZMgslmXp6tWrdseAC1iWpdGj3tT6dV9p1twPVKRoMbsjGcvWslqoUCFNnjxZkZGRt1weGxurcErXHY17a4xq1amrQoUK69y5P+esXrp4Uc2aR9odDXdpxuTxerhaTeUvUFCXL1/S+jWrFLsjRm9NnCa/nDkVWrmKpk58Rz6+PipQsLB27dim/65coV69B9gdHU7UvkMnDXlloEIqVFClSmFa9tESxcXF6anWXE83q5k4fpxq1KylAgUL6vKlS1q9aqW2xWzV5Gmz7I4GFxg1YrhWrfxC4ydOkZ+fX+o89Jw5c8nX19fmdGaxtayGh4drx44dty2r/3TUFdJvv/2mqIH99Pv535Unbx5VfLCS3l+4RIULF7E7Gu7SuXNnNXJYlM7Gn5FfzlwqFVxGb02cpoceriZJGjbybc2YPF5vDn1FFy4kqGDBwura/SU1b9na5uRwpkaNmyjh9/OaMXWKzpw5reDSZTR52gw+41nQubPxGhI1UPFnTitnrlwqU6asJk+bpYhqXOEjK/poySJJUpdO7dOMDx8RreaRT9oRyVi2Xmf122+/1aVLl9SoUaNbLr906ZK2bdum2rUzdvcOd54G4I7c6TqrcL/rrLo7jlcAWVd6r7PKTQFwz6OsuhfKqnvJev9CAbiBmwIAAADgnkdZBQAAgLEoqwAAADAWZRUAAADGoqwCAADAWJRVAAAAGIuyCgAAAGNRVgEAAGAsyioAAACMRVkFAACAsSirAAAAMBZlFQAAAMairAIAAMBYlFUAAAAYi7IKAAAAY1FWAQAAYCzKKgAAAIxFWQUAAICxKKsAAAAwFmUVAAAAxqKsAgAAwFiUVQAAABiLsgoAAABjUVYBAABgLMoqAAAAjEVZBQAAgLEoqwAAADAWZRUAAADGoqwCAADAWJRVAAAAGIuyCgAAAGNRVgEAAGAsyioAAACMRVkFAACAsSirAAAAMBZlFQAAAMairAIAAMBYlFUAAAAYi7IKAAAAY1FWAQAAYCyHZVmW3SGc7cp1uxMAcJXklCz3lYU78PRw2B0BgIv4ZkvfehxZBQAAgLEoqwAAADAWZRUAAADGoqwCAADAWJRVAAAAGIuyCgAAAGNRVgEAAGAsyioAAACMRVkFAACAsSirAAAAMBZlFQAAAMairAIAAMBYGS6rq1ev1nfffZf6ePLkyQoNDdXTTz+t8+fPOzUcAAAA3FuGy+qAAQN04cIFSdLu3bvVr18/NWnSREeOHFHfvn2dHhAAAADuK1tGn3D06FGFhIRIkpYtW6bHH39co0aN0o4dO9SkSROnBwQAAID7yvCRVW9vb12+fFmStHbtWjVs2FCSlDdv3tQjrgAAAIAzZPjIao0aNdS3b19Vr15dW7du1ZIlSyRJhw4dUtGiRZ0eEAAAAO4rw0dWJ02apGzZsunjjz/W1KlTVaRIEUnSqlWr1KhRI6cHBAAAgPtyWJZl2R3C2a5ctzsBAFdJTslyX1m4A08Ph90RALiIbzp/v5/hI6s7duzQ7t27Ux9/9tlnioyM1ODBg3X16tWMbg4AAAC4rQyX1eeff16HDh2SJB05ckRt2rRRjhw59NFHH2ngwIFODwgAAAD3leGyeujQIYWGhkqSPvroI9WqVUsLFy7UvHnztGzZMmfnAwAAgBvLcFm1LEspKSmS/rx01Y1rqxYrVkzx8fHOTQcAAAC3luGyWqVKFY0YMUIffPCBNm7cqKZNm0r682YBBQoUcHpAAAAAuK8Ml9Xx48drx44d6tWrl4YMGaLg4GBJ0scff6xq1ao5PSAAAADcl9MuXXXlyhV5enrKy8vLGZu7uyxcugrIsrh0lXvh0lVA1pXeS1dl+A5Wt31BX19nbQoAAACQ9C/KanJyst59910tXbpUJ06cuOnaqufOnXNaOAAAALi3DM9ZHT58uMaNG6dWrVopISFBffv21ZNPPikPDw+9/vrrLogIAAAAd5XhOaulSpXSxIkT1bRpU+XKlUuxsbGpY1u2bNHChQtdlTXdmLMKZF3MWXUvzFkFsi6X3W711KlTqlixoiQpZ86cSkhIkCQ9/vjj+vLLLzO6OQAAAOC2MlxWixYtqri4OElScHCw1qxZI0mKiYmRj4+Pc9MBAADArWW4rLZo0ULr1q2TJL388ssaOnSoSpcurWeffVbPPfec0wMCAADAfd31dVa3bNmiTZs2KTg4WE888YSzct0V5qwCWRdzVt0Lc1aBrCu9c1addlMAk1BWgayLsupeKKtA1uXUmwKsWLEi3S9sytFVAAAA3PvSdWTVwyN9U1sdDoeSk5PvOtTd4sgqkHVxZNW9cGQVyLqcemQ1JSXlbrIAAAAA/0qGrwYAAAAAZJZ0l9X169crJCREFy5cuGlZQkKCHnjgAX3zzTdODYf0W7JogRo3rKeHwiqqzVNPasf2bXZHgguxv93D9evXNXnieD3eqL4iqlRSs0YNNGPqZH7blUVt3xajF3u8oAZ1aqjSA2W1ft1auyMhE/B9/s/SXVbHjx+vrl27yt/f/6ZlAQEBev755/Xuu+86NRzSZ/WqlRo7Olpdu3XXko+Xq3LlcPV4vqvifv3V7mhwAfa3+5g3Z5aWfbRYgwYP1bLPvtTLfftr/rzZWrzwQ7ujwQUSEy+rbNmyemXIa3ZHQSbh+zx90l1Wd+3apUaNGt12ecOGDbV9+3anhELGfPD+XLVo2VJP/ucp3V+qlAZGDVHBQgW1dMkiu6PBBdjf7uPHXTtVu2591axVR4WLFFWDho30SLXq2rd3j93R4AI1atZWr5f7qMGjDe2OgkzC93n6pLus/vbbb/Ly8rrt8mzZsunMmTNOCYX0u3b1qvbv26uIajXSjEdUq65dsTttSgVXYX+7l7CwcG39YbOOHzsqSTp08IBid+xQjZq1bE4G4G7xfZ5+6bxogFSkSBHt3r1bwcHBt1z+448/qlChQk4LhvQ5//t5JScnKzAwMM14YGCQ4uP5z0NWw/52Lx07d9XFi3/oySeayNPTU8nJyer5Um81avK43dEA3CW+z9Mv3UdWmzRpotdee01Xrly5aVliYqKGDRumxx/P+BdoYmKivvvuO+3bt++mZVeuXNH8+fPv+PykpCRduHAhzU9SUlKGc9zrHI601yK0LOumMWQd7G/3sGb1Sq384nONGvO2FixZpuEjR+uDeXP0+Wef2h0NgJPwff7P0l1WX331VZ07d05lypTR2LFj9dlnn2nFihUaM2aMypYtq3PnzmnIkCEZevFDhw6pfPnyqlWrlipWrKg6deooLi4udXlCQoI6dep0x21ER0crICAgzc9bY6IzlONelid3Hnl6eio+Pj7N+LlzZxUYGGRTKrgK+9u9jH/nLXXs3FWPNW6q0mXK6vFmzdWufUfNnTXD7mgA7hLf5+mX7rJaoEABbdq0SRUqVFBUVJRatGihyMhIDR48WBUqVND333+vAgUKZOjFBw0apIoVK+r06dM6ePCg/P39Vb16dZ04cSLd24iKilJCQkKanwGDojKU417m5e2t8iEPaMum79OMb9m0SZVCw2xKBVdhf7uXK1cSb7qDoIenh1IsLl0F3Ov4Pk+/dM9ZlaQSJUpo5cqVOn/+vA4fPizLslS6dGnlyZPnX734pk2btHbtWgUFBSkoKEgrVqxQz549VbNmTW3YsEF+fn7/uA0fHx/5+PikGXO3262279BJQ14ZqJAKFVSpUpiWfbREcXFxeqp1G7ujwQXY3+6jVu26mj1jmgoWKqRSpYJ14MB+fTh/nppHtrQ7Glzg8qVLaQ7W/PLzzzqwf78CAgJUqHBhG5PBVfg+Tx+HZVm23Wjb399fP/zwg8qXL59m/MUXX9Ty5cu1cOFC1alTR8nJyRnarruVVenPiwrPmzNbZ86cVnDpMhowKErhVR6yOxZcxJ33d3KKbV9Zme7SpYuaMmmiNqxbq/Pnzipfvvx6rHFTdeveQ15e3nbHyxSeHu4zdy9m6w/q0unZm8afaN5Cb44abUMiZAZ3/j73TechU1vLatWqVfXiiy+qffv2Ny3r1auXFixYoAsXLlBWAaRyp7IK9yqrgLtJb1lN95xVV2jRooUWLbr1hW8nTZqktm3bysYuDQAAAJvZemTVVTiyCmRdHFl1LxxZBbKue+LIKgAAAHAn/6qsfvDBB6pevboKFy6s48ePS5LGjx+vzz77zKnhAAAA4N4yXFanTp2qvn37qkmTJvr9999TT37KnTu3xo8f7+x8AAAAcGMZLqvvvfeeZs6cqSFDhsjT0zN1vEqVKtq9e7dTwwEAAMC9ZbisHj16VGFhN99ZwcfHR5cuXXJKKAAAAED6F2W1ZMmSio2NvWl81apVCgkJcUYmAAAAQFIGb7cqSQMGDFDPnj115coVWZalrVu3atGiRYqOjtasWbNckREAAABu6l9dZ3XmzJkaMWKETp48KUkqUqSIXn/9dXXu3NnpAf8NrrMKZF1cZ9W9cJ1VIOvKlNutxsfHKyUlRfnz5/+3m3AJyiqQdVFW3QtlFci6MqWsmoqyCmRdlFX3QlkFsq70ltUMz1ktWbKkHI7bf3kcOXIko5sEAAAAbinDZbV3795pHl+7dk07d+7U6tWrNWDAAGflAgAAAJw3DWDy5Mnatm2b5s6d64zN3RWmAQBZF9MA3AvTAICsK9PnrB45ckShoaG6cOGCMzZ3VyirQNZFWXUvlFUg60pvWc3wTQFu5+OPP1bevHmdtTkAAAAg43NWw8LC0pxgZVmWTp06pTNnzmjKlClODQcAAAD3luGyGhkZmeaxh4eH8uXLpzp16qhcuXLOygUAAABkrKxev35d9913nx577DEVLFjQVZkAAAAASf/iBKscOXJo//79KlGihKsy3TVOsAKyLk6wci+cYAVkXS47werhhx/Wzp07M/o0AAAAIMMyPGe1R48e6tevn37++WeFh4fLz88vzfIHH3zQaeEAAADg3tI9DeC5557T+PHjlTt37ps34nDIsiw5HA4lJyc7O2OGMQ0AyLqYBuBemAYAZF1OvymAp6en4uLilJiYeMf1TJjLSlkFsi7KqnuhrAJZV3rLarqnAdzotCaUUQAAALiHDJ1g9debAQAAAACulu5pAB4eHgoICPjHwnru3DmnBLsbTAMAsi6mAbgXpgEAWZfTpwFI0vDhwxUQEPBv8gAAAAAZlqEjq6dOnVL+/PldnemucWQVyLo4supeOLIKZF1OvykA81UBAACQ2dJdVjN4V1YAAADgrqV7zmpKSoorcwAAAAA3ydClqwAAAIDMRFkFAACAsSirAAAAMBZlFQAAAMairAIAAMBYlFUAAAAYi7IKAAAAY1FWAQAAYKx03xTgXnI9mbttuRPuHe5ePLj1s1tJvJpsdwRkouzennZHgIE4sgoAAABjUVYBAABgLMoqAAAAjEVZBQAAgLEoqwAAADAWZRUAAADGoqwCAADAWJRVAAAAGIuyCgAAAGNRVgEAAGAsyioAAACMRVkFAACAsSirAAAAMBZlFQAAAMairAIAAMBYlFUAAAAYi7IKAAAAY1FWAQAAYCzKKgAAAIxFWQUAAICxKKsAAAAwFmUVAAAAxqKsAgAAwFiUVQAAABiLsgoAAABjUVYBAABgLMoqAAAAjEVZBQAAgLEoqwAAADAWZRUAAADGoqwCAADAWJRVAAAAGIuyCgAAAGNRVgEAAGAsyioAAACMRVkFAACAsSirAAAAMBZlFQAAAMairAIAAMBYlFUAAAAYi7J6j9mxLUa9e72gx+rXVPiD5bRh/do0y9evXaOeL3RWvVqPKPzBcjp4YL9NSeEKs2dO19OtW6pa1TDVrRWh3i/10LGjR+yOBRdZunihnmrRTNUfrqzqD1fWs+1a67tvN9odC07w/uwZ6tSulepVr6LG9WpoYJ9eOn7s6G3XHz1imB4JC9HiBfMzMSUyw5JFC9S4YT09FFZRbZ56Uju2b7M7knEoq/eYxMRElSlbToOiht52eaXQynrx5X6ZnAyZYfu2rWrdtp3mL1yqaTPmKvl6srp366zEy5ftjgYXKFCwoF7q018LlyzTwiXL9FDVR9T7xZ46fPh/dkfDXdq5Y5tatm6rWfMXaeLUWUpOTtbL3bsoMfHmz/LGDWu1d/ePypcvvw1J4UqrV63U2NHR6tqtu5Z8vFyVK4erx/NdFffrr3ZHM4rDsizL7hDOdjEpy72lWwp/sJzeHj9Jdes1uGnZr7/8rGaNG2jh0k9Vtlx5G9JlHk8Ph90RbHPu3DnVqxWh2fM+VHiVh+yOg0xQq1pV9ek3QC1aPmV3lExx5Vqy3REyxflz59S4fg1NnTVfYeFVUsdPn/5Nndu30YQpM9T3xe5q0+5ZtWn3rI1JXSu7t6fdETJVuzZPqXxIiF59bXjqWGSzxqpbr4Fe7pP1Dzr5ZkvfehxZBe5hFy/+IUkKCAiwOQlcLTk5WatXfqnExMt6MDTM7jhwshufZf+/fJZTUlI0/NVX9EyH53R/qdJ2RYOLXLt6Vfv37VVEtRppxiOqVdeu2J02pTJTOjut6+zfv19btmxRRESEypUrpwMHDmjChAlKSkrSM888o3r16t3x+UlJSUpKSkozdk3e8vHxcWVswHaWZemdsdEKqxyu4NJl7I4DF/nfoYN6tl0bXb2apOw5cmjchMkqVSrY7lhwIsuyNOGdsaoUVlmlgv+vlH4wd5Y8PT3Vqu0zNqaDq5z//bySk5MVGBiYZjwwMEjx8WdsSmUmW4+srl69WqGhoerfv7/CwsK0evVq1apVS4cPH9aJEyf02GOPaf369XfcRnR0tAICAtL8vDM2OpPeAWCf6JFv6NChQxo9dpzdUeBC95UsqSXLlmv+giVq1aqtXhsySD/9dNjuWHCit0eP0OH/HdSb0W+njh3Yt1dLFn2gocNHyeFw36lO7uDv+9eyLPb539haVt944w0NGDBAZ8+e1dy5c/X000+ra9eu+uqrr7R27VoNHDhQo0ePvuM2oqKilJCQkOan38CoTHoHgD1Gj3pTGzes16w576tAwYJ2x4ELeXl5q3jxEnqgQkW91KefypQtp4UfckZ4VvH26BH6duMGTZk5T/kL/N9nOXbndp0/d06RTeqrepWKql6lok7F/aqJ48YqssnN5yng3pMndx55enoqPj4+zfi5c2cVGBhkUyoz2ToNYO/evZo//88v3VatWql9+/Zq2bJl6vK2bdtq9uzZd9yGj4/PTb/yd5cTrOB+LMvS6FFvav26rzRr7gcqUrSY3ZGQySzL0tWrV+2OgbtkWZbeGTNSG9ev1eSZ81S4SNE0yxs3fUIPPRyRZqx3j65q1PQJPd68RWZGhYt4eXurfMgD2rLpe9Vv8Gjq+JZNm1SnXn0bk5nH9jmrN3h4eMjX11e5c+dOHcuVK5cSEhLsC2Wgy5cv6eSJE6mPf/3lZx08sF/+AQEqVKiwEhJ+16m4OJ05c1qSUq/bFxgUpKCgfLZkhvOMGjFcq1Z+ofETp8jPzy91XlPOnLnk6+trczo428Tx41SjZi0VKFhQly9d0upVK7UtZqsmT5tldzTcpbei39SaVV9q7LuT5Ofnp7P//7Ps9/8/ywG5cyvgL/8eSpJntmwKDApSiftK2pAYrtC+QycNeWWgQipUUKVKYVr20RLFxcXpqdZt7I5mFFvL6n333afDhw8rOPjPkwU2b96s4sWLpy4/efKkChUqZFc8I+3bu0fPd+6Q+njcW39Ok3j8iUgNHzFaG79er+FDB6cujxrYV5LU7YWeer7Hi5kbFk730ZJFkqQundqnGR8+IlrNI5+0IxJc6NzZeA2JGqj4M6eVM1culSlTVpOnzVJEtep2R8Nd+uSjxZKkHl07pBl/dfhIPf4ER07dRaPGTZTw+3nNmDpFZ86cVnDpMpo8bYYKFy5idzSj2Hqd1WnTpqlYsWJq2rTpLZcPGTJEv/32m2bNythRBKYBuBd3vs4qkNW5y3VW8Sd3u86qu0vvdVa5KQDueZRVIOuirLoXyqp74aYAAAAAuOdRVgEAAGAsyioAAACMRVkFAACAsSirAAAAMBZlFQAAAMairAIAAMBYlFUAAAAYi7IKAAAAY1FWAQAAYCzKKgAAAIxFWQUAAICxKKsAAAAwFmUVAAAAxqKsAgAAwFiUVQAAABiLsgoAAABjUVYBAABgLMoqAAAAjEVZBQAAgLEoqwAAADAWZRUAAADGoqwCAADAWJRVAAAAGIuyCgAAAGNRVgEAAGAsyioAAACMRVkFAACAsSirAAAAMBZlFQAAAMairAIAAMBYlFUAAAAYi7IKAAAAY1FWAQAAYCzKKgAAAIxFWQUAAICxKKsAAAAwFmUVAAAAxqKsAgAAwFjZ7A7gCpYsuyMgEzkcDrsjAHCR7N6edkdAJvrlfKLdEZCJSuXLnq71OLIKAAAAY1FWAQAAYCzKKgAAAIxFWQUAAICxKKsAAAAwFmUVAAAAxqKsAgAAwFiUVQAAABiLsgoAAABjUVYBAABgLMoqAAAAjEVZBQAAgLEoqwAAADAWZRUAAADGoqwCAADAWJRVAAAAGIuyCgAAAGNRVgEAAGAsyioAAACMRVkFAACAsSirAAAAMBZlFQAAAMairAIAAMBYlFUAAAAYi7IKAAAAY1FWAQAAYCzKKgAAAIxFWQUAAICxKKsAAAAwFmUVAAAAxqKsAgAAwFiUVQAAABiLsgoAAABjUVYBAABgLMoqAAAAjEVZBQAAgLEoqwAAADAWZRUAAADGoqwCAADAWJRVAAAAGIuyeo/ZsS1GfXp1V6P6tVTlwfL6ev3a1GXXr13TxHffVusnn1CNqpXVqH4tvTZ4kM6cPm1jYrjCkkUL1LhhPT0UVlFtnnpSO7ZvszsSXIj97V7Y31lT/Jnf9NYbg9W6SW21qP+IenVspf8d2Je6PPHyZU0ZF632LRoqst7Der5dC3356VIbE5uDsnqPSUxMVOmyZTUw6tWbll25ckUH9u9Tl+e768Mly/TWuIk6cfyY+r7Uw4akcJXVq1Zq7Ohode3WXUs+Xq7KlcPV4/muivv1V7ujwQXY3+6F/Z01/XHhgvp37yjPbNn0xtuTNO3DZerSq59y5sqVus6M997S9h82acDQkZq+4BNFtmqnqePHaPO3G2xMbgaHZVmW3SGc7Y+kFLsjZIoqD5bX2+PfU516DW67zt49u9Xh6Vb64r/rVLBQ4UxMl3m8PN3r/1zt2jyl8iEhevW14aljkc0aq269Bnq5Tz8bk8EV2N/uxd339y/nE+2O4BJzp07Qvt2xemvK3Nuu0719S9Ws/5ie7tgtdeyl59qqSkQNPdu1Z2bEzHSl8mVP13rG/SufBbuzrS5e/EMOh0M5c/nbHQVOcO3qVe3ft1cR1WqkGY+oVl27YnfalAquwv52L+zvrGvL9xtVulyIRr3aX20fr6tenVpr9YpladYJeTBMP3z3teLP/CbLsrRrR4x+OXlc4VWr2ZTaHNnsDvB3Pj4+2rVrl8qXL293lHteUlKSJo0fp0ZNHlfOnDntjgMnOP/7eSUnJyswMDDNeGBgkOLjz9iUCq7C/nYv7O+s69SvP+vL5R+pRetn1PrZLjq4b4+mjR8rLy9v1W/cTJL0Qu9BmjhmuJ5t8Zg8PbPJ4eHQy4OG6YFKYTant59tZbVv3763HE9OTtbo0aNTP6zjxo2743aSkpKUlJSUZuyqvOTj4+OcoPeo69euafDAfkpJSdGgIa/ZHQdO5nA40jy2LOumMWQd7G/3wv7OeqyUFJUuF6KOz78kSSpVppxOHPtJXy7/KLWsrvhooQ7s3a1hoycof8FC2rNrh6a8M0p5A4MU9tAjdsa3nW1ldfz48apUqZJy586dZtyyLO3fv19+fn7p+nBGR0dr+PDhacZeGfKaBg8d5sy495Tr167plQF99OsvP2vqrLkcVc1C8uTOI09PT8XHx6cZP3furAIDg2xKBVdhf7sX9nfWlScwn4rdVyrNWLESJfX9139e0Scp6Yren/GeXh01TlWr1ZIklQwuo5/+d1CfLJrv9mXVtjmrI0eOVEJCgoYOHaoNGzak/nh6emrevHnasGGD1q9f/4/biYqKUkJCQpqffgNfyYR3YKYbRfXE8eOaMmOOcufOY3ckOJGXt7fKhzygLZu+TzO+ZdMmVQrlV0VZDfvbvbC/s66QipX0y4ljacZ+OXlc+QsWkiQlX7+u69evy+FIW8s8PTyUYrnHSeN3YtuR1aioKDVo0EDPPPOMmjVrpujoaHl5eWV4Oz4+Pjf9yj8rXw3g8uVLOnniROrjX375WQcP7FdAQICC8uXXwH69dXD/Pr07aaqSU5JT5zkFBATIy8vbrthwovYdOmnIKwMVUqGCKlUK07KPliguLk5PtW5jdzS4APvbvbC/s6YWrZ9Rvxc6asn8WapZr6EO7tujVSuW6aWBQyVJOfxyqmJouOZMeVc+Pj7KX7Cwdsdu07rVX6jri1n/KhD/xPZLV128eFE9e/bUzp07tWDBAoWHhys2NlYhISH/eptZuaxui9mqFzp3uGn88Sci1a17Lz3R+NaXsZo2+31Veaiqq+PZwt0uXSX9edHweXNm68yZ0wouXUYDBkUpvMpDdseCi7C/3Ys77++seukqSfrh+280b/pE/frzCRUsVEQtWj+jRk+0TF1+7my85k2fqJ1bN+uPCxeUv2AhNXqipVq0fibLzllO76WrbC+rNyxevFi9e/fWmTNntHv3bsoq0s0dyyoAZEVZuaziZvdcWZWkn3/+Wdu3b1eDBg3k5+f3r7dDWXUvlFUAyBooq+7lniyrzkJZdS+UVQDIGiir7uWevYMVAAAAcANlFQAAAMairAIAAMBYlFUAAAAYi7IKAAAAY1FWAQAAYCzKKgAAAIxFWQUAAICxKKsAAAAwFmUVAAAAxqKsAgAAwFiUVQAAABiLsgoAAABjUVYBAABgLMoqAAAAjEVZBQAAgLEoqwAAADAWZRUAAADGoqwCAADAWJRVAAAAGIuyCgAAAGNRVgEAAGAsyioAAACMRVkFAACAsSirAAAAMBZlFQAAAMairAIAAMBYlFUAAAAYi7IKAAAAY1FWAQAAYCzKKgAAAIxFWQUAAICxKKsAAAAwFmUVAAAAxqKsAgAAwFiUVQAAABiLsgoAAABjUVYBAABgLMoqAAAAjOWwLMuyOwTuXlJSkqKjoxUVFSUfHx+748DF2N/uhf3tXtjf7oX9/c8oq1nEhQsXFBAQoISEBPn7+9sdBy7G/nYv7G/3wv52L+zvf8Y0AAAAABiLsgoAAABjUVYBAABgLMpqFuHj46Nhw4YxOdtNsL/dC/vbvbC/3Qv7+59xghUAAACMxZFVAAAAGIuyCgAAAGNRVgEAAGAsyioAAACMRVnNIqZMmaKSJUvK19dX4eHh+vbbb+2OBBf45ptv1KxZMxUuXFgOh0PLly+3OxJcKDo6Wg899JBy5cql/PnzKzIyUgcPHrQ7Flxk6tSpevDBB+Xv7y9/f39FRERo1apVdsdCJomOjpbD4VDv3r3tjmIcymoWsGTJEvXu3VtDhgzRzp07VbNmTTVu3FgnTpywOxqc7NKlS6pUqZImTZpkdxRkgo0bN6pnz57asmWLvvrqK12/fl0NGzbUpUuX7I4GFyhatKhGjx6tbdu2adu2bapXr56aN2+uvXv32h0NLhYTE6MZM2bowQcftDuKkbh0VRbw8MMPq3Llypo6dWrqWPny5RUZGano6Ggbk8GVHA6HPv30U0VGRtodBZnkzJkzyp8/vzZu3KhatWrZHQeZIG/evHrrrbfUuXNnu6PARS5evKjKlStrypQpGjFihEJDQzV+/Hi7YxmFI6v3uKtXr2r79u1q2LBhmvGGDRtq06ZNNqUC4AoJCQmS/iwwyNqSk5O1ePFiXbp0SREREXbHgQv17NlTTZs2VYMGDeyOYqxsdgfA3YmPj1dycrIKFCiQZrxAgQI6deqUTakAOJtlWerbt69q1KihChUq2B0HLrJ7925FREToypUrypkzpz799FOFhITYHQsusnjxYm3fvl3btm2zO4rRKKtZhMPhSPPYsqybxgDcu3r16qUff/xR3333nd1R4EJly5ZVbGysfv/9dy1btkwdOnTQxo0bKaxZ0MmTJ/Xyyy9rzZo18vX1tTuO0Sir97igoCB5enredBT19OnTNx1tBXBvevHFF7VixQp98803Klq0qN1x4ELe3t4KDg6WJFWpUkUxMTGaMGGCpk+fbnMyONv27dt1+vRphYeHp44lJyfrm2++0aRJk5SUlCRPT08bE5qDOav3OG9vb4WHh+urr75KM/7VV1+pWrVqNqUC4AyWZalXr1765JNPtH79epUsWdLuSMhklmUpKSnJ7hhwgfr162v37t2KjY1N/alSpYratWun2NhYiupfcGQ1C+jbt6/at2+vKlWqKCIiQjNmzNCJEyf0wgsv2B0NTnbx4kUdPnw49fHRo0cVGxurvHnzqnjx4jYmgyv07NlTCxcu1GeffaZcuXKl/gYlICBA2bNntzkdnG3w4MFq3LixihUrpj/++EOLFy/W119/rdWrV9sdDS6QK1eum+af+/n5KTAwkHnpf0NZzQJat26ts2fP6o033lBcXJwqVKiglStXqkSJEnZHg5Nt27ZNdevWTX3ct29fSVKHDh00b948m1LBVW5cjq5OnTppxufOnauOHTtmfiC41G+//ab27dsrLi5OAQEBevDBB7V69Wo9+uijdkcDbMV1VgEAAGAs5qwCAADAWJRVAAAAGIuyCgAAAGNRVgEAAGAsyioAAACMRVkFAACAsSirAAAAMBZlFQAAAMairALAXXr99dcVGhqa+rhjx46KjIzM9BzHjh2Tw+FQbGysEdsBAGegrALIkjp27CiHwyGHwyEvLy/df//96t+/vy5duuTy154wYUK6b39rRzE8fPiwOnXqpKJFi8rHx0clS5ZU27ZttW3btkzLAADpRVkFkGU1atRIcXFxOnLkiEaMGKEpU6aof//+t1z32rVrTnvdgIAA5c6d22nbc6Zt27YpPDxchw4d0vTp07Vv3z59+umnKleunPr162d3PAC4CWUVQJbl4+OjggULqlixYnr66afVrl07LV++XNL//ep+zpw5uv/+++Xj4yPLspSQkKBu3bopf/788vf3V7169bRr16402x09erQKFCigXLlyqXPnzrpy5Uqa5X+fBpCSkqIxY8YoODhYPj4+Kl68uEaOHClJKlmypCQpLCxMDodDderUSX3e3LlzVb58efn6+qpcuXKaMmVKmtfZunWrwsLC5OvrqypVqmjnzp13/PuwLEsdO3ZU6dKl9e2336pp06YqVaqUQkNDNWzYMH322We3fF5ycrI6d+6skiVLKnv27CpbtqwmTJiQZp2vv/5aVatWlZ+fn3Lnzq3q1avr+PHjkqRdu3apbt26ypUrl/z9/RUeHs5RXADpls3uAACQWbJnz57mCOrhw4e1dOlSLVu2TJ6enpKkpk2bKm/evFq5cqUCAgI0ffp01a9fX4cOHVLevHm1dOlSDRs2TJMnT1bNmjX1wQcfaOLEibr//vtv+7pRUVGaOXOm3n33XdWoUUNxcXE6cOCApD8LZ9WqVbV27Vo98MAD8vb2liTNnDlTw4YN06RJkxQWFqadO3eqa9eu8vPzU4cOHXTp0iU9/vjjqlevnj788EMdPXpUL7/88h3ff2xsrPbu3auFCxfKw+PmYxW3OxqckpKiokWLaunSpQoKCtKmTZvUrVs3FSpUSK1atdL169cVGRmprl27atGiRbp69aq2bt0qh8MhSWrXrp3CwsI0depUeXp6KjY2Vl5eXnfMCgCpLADIgjp06GA1b9489fEPP/xgBQYGWq1atbIsy7KGDRtmeXl5WadPn05dZ926dZa/v7915cqVNNsqVaqUNX36dMuyLCsiIsJ64YUX0ix/+OGHrUqVKt3ytS9cuGD5+PhYM2fOvGXOo0ePWpKsnTt3phkvVqyYtXDhwjRjb775phUREWFZlmVNnz7dyps3r3Xp0qXU5VOnTr3ltm5YsmSJJcnasWPHLZf/U6a/6tGjh9WyZUvLsizr7NmzliTr66+/vuW6uXLlsubNm3fH1wSA22EaAIAs64svvlDOnDnl6+uriIgI1apVS++9917q8hIlSihfvnypj7dv366LFy8qMDBQOXPmTP05evSofvrpJ0nS/v37FRERkeZ1/v74r/bv36+kpCTVr18/3bnPnDmjkydPqnPnzmlyjBgxIk2OSpUqKUeOHOnKIf05DUBS6hHPjJg2bZqqVKmifPnyKWfOnJo5c6ZOnDghScqbN686duyoxx57TM2aNdOECRMUFxeX+ty+ffuqS5cuatCggUaPHp36HgAgPSirALKsunXrKjY2VgcPHtSVK1f0ySefKH/+/KnL/fz80qyfkpKiQoUKKTY2Ns3PwYMHNWDAgH+VIXv27Bl+TkpKiqQ/pwL8NceePXu0ZcsWSf9XPDOiTJkykv4suhmxdOlS9enTR88995zWrFmj2NhYderUSVevXk1dZ+7cudq8ebOqVaumJUuWqEyZMqlZX3/9de3du1dNmzbV+vXrFRISok8//TTD+QG4J8oqgCzLz89PwcHBKlGiRLrmSFauXFmnTp1StmzZFBwcnOYnKChIklS+fPnUEnbD3x//VenSpZU9e3atW7fulstvzFFNTk5OHStQoICKFCmiI0eO3JTjxglZISEh2rVrlxITE9OVQ5JCQ0MVEhKid955J7UQ/9Xvv/9+y+d9++23qlatmnr06KGwsDAFBwff8uhoWFiYoqKitGnTJlWoUEELFy5MXVamTBn16dNHa9as0ZNPPqm5c+feMSsA3EBZBYD/r0GDBoqIiFBkZKT++9//6tixY9q0aZNeffXV1LPXX375Zc2ZM0dz5szRoUOHNGzYMO3du/e22/T19dWgQYM0cOBAzZ8/Xz/99JO2bNmi2bNnS5Ly58+v7Nmza/Xq1frtt9+UkJAg6c+jkdHR0ZowYYIOHTqk3bt3a+7cuRo3bpwk6emnn5aHh4c6d+6sffv2aeXKlXr77bfv+P4cDofmzp2rQ4cOqVatWlq5cqWOHDmiH3/8USNHjlTz5s1v+bzg4GBt27ZN//3vf3Xo0CENHTpUMTExqcuPHj2qqKgobd68WcePH9eaNWt06NAhlS9fXomJierVq5e+/vprHT9+XN9//71iYmJUvnz59O8YAO7N7kmzAOAKfz/B6u+GDRuW5qSoGy5cuGC9+OKLVuHChS0vLy+rWLFiVrt27awTJ06krjNy5EgrKCjIypkzp9WhQwdr4MCBtz3ByrIsKzk52RoxYoRVokQJy8vLyypevLg1atSo1OUzZ860ihUrZnl4eFi1a9dOHV+wYIEVGhpqeXt7W3ny5LFq1aplffLJJ6nLN2/ebFWqVMny9va2QkNDrWXLlv3jiVGWZVkHDx60nn32Watw4cKWt7e3VaJECatt27apJ179/QSrK1euWB07drQCAgKs3LlzW927d7deeeWV1Pd86tQpKzIy0ipUqFDq9l577TUrOTnZSkpKstq0aWMVK1bM8vb2tgoXLmz16tXLSkxMvGNGALjBYVn/YuITAAAAkAmYBgAAAABjUVYBAABgLMoqAAAAjEVZBQAAgLEoqwAAADAWZRUAAADGoqwCAADAWJRVAAAAGIuyCgAAAGNRVgEAAGAsyioAAACM9f8A1zmAGjdsdqkAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 800x600 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from sklearn.ensemble import GradientBoostingClassifier\n",
    "from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "# Load the training data from the first CSV file\n",
    "train_data = pd.read_csv(r\"C:\\Users\\KIIT\\Desktop\\Iterations\\iter2\\Combined_6.csv\")\n",
    "\n",
    "# Split the features and target variable\n",
    "X_train = train_data.drop('Facies', axis=1)\n",
    "y_train = train_data['Facies']\n",
    "\n",
    "# Load the test data from the second CSV file\n",
    "test_data = pd.read_csv(r\"C:\\Users\\KIIT\\Desktop\\SB-10.csv\")\n",
    "\n",
    "# Split the features and target variable\n",
    "X_test = test_data.drop('Facies', axis=1)\n",
    "y_test = test_data['Facies']\n",
    "\n",
    "# Define the parameters for the gradient boosting classifier\n",
    "params = {\n",
    "    'n_estimators': 163,\n",
    "    'learning_rate': 0.016258128550853512,\n",
    "    'max_depth': 53,\n",
    "    'min_samples_split': 203,\n",
    "    'min_samples_leaf': 205,\n",
    "    'subsample': 0.9990808801724966\n",
    "}\n",
    "\n",
    "\n",
    "\n",
    "# Create a gradient boosting classifier object with the defined parameters\n",
    "gb_classifier = GradientBoostingClassifier(**params)\n",
    "\n",
    "# Train the classifier\n",
    "gb_classifier.fit(X_train, y_train)\n",
    "\n",
    "# Predict on the test set\n",
    "y_pred = gb_classifier.predict(X_test)\n",
    "\n",
    "# Calculate the accuracy of the classifier\n",
    "accuracy = accuracy_score(y_test, y_pred)\n",
    "\n",
    "# Print the accuracy\n",
    "print(\"Accuracy:\", accuracy)\n",
    "\n",
    "# Calculate the confusion matrix\n",
    "cm = confusion_matrix(y_test, y_pred)\n",
    "\n",
    "# Print the confusion matrix\n",
    "print(\"Confusion Matrix:\")\n",
    "print(cm)\n",
    "\n",
    "# Get predicted probabilities\n",
    "y_prob = gb_classifier.predict_proba(X_test)\n",
    "\n",
    "# Calculate the area under the ROC curve\n",
    "roc_auc = roc_auc_score(y_test, y_prob, multi_class='ovr')\n",
    "\n",
    "# Print the area under the ROC curve\n",
    "print(\"Area Under ROC Curve:\", roc_auc)\n",
    "\n",
    "# Plot the confusion matrix\n",
    "plt.figure(figsize=(8, 6))\n",
    "sns.heatmap(cm, annot=True, cmap=\"Blues\", fmt=\"d\", cbar=False)\n",
    "plt.title(\"Confusion Matrix\")\n",
    "plt.xlabel(\"Predicted Class\")\n",
    "plt.ylabel(\"True Class\")\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "dffcf4ae",
   "metadata": {},
   "source": [
    "### Optimization"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a2ad07ad",
   "metadata": {},
   "source": [
    "### simulated annealing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "2f8f421b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Optimized Parameters:\n",
      "n_estimators: 100\n",
      "learning_rate: 0.1\n",
      "max_depth: 3\n",
      "min_samples_split: 2\n",
      "min_samples_leaf: 1\n",
      "subsample: 1.0\n",
      "Best Parameters: {'n_estimators': 100, 'learning_rate': 0.1, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 1, 'subsample': 1.0}\n",
      "Best Accuracy: 0.8945086705202312\n",
      "Accuracy: 0.9046242774566474\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from sklearn.ensemble import GradientBoostingClassifier\n",
    "from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import numpy as np\n",
    "\n",
    "# Function to calculate the objective value (e.g., accuracy, F1 score)\n",
    "def calculate_objective_value(y_true, y_pred):\n",
    "    return accuracy_score(y_true, y_pred)\n",
    "\n",
    "# Function to generate a random neighbor solution\n",
    "def generate_neighbor_solution(params, temperature):\n",
    "    neighbor_params = params.copy()\n",
    "    for param_name in params:\n",
    "        value = params[param_name]\n",
    "        if param_name == 'max_depth':\n",
    "            range_min = max(1, value - int(temperature))\n",
    "            range_max = value + int(temperature)\n",
    "            neighbor_params[param_name] = np.random.randint(range_min, range_max + 1)\n",
    "        elif param_name == 'min_samples_leaf':\n",
    "            if isinstance(value, int):\n",
    "                range_min = max(1, value - int(temperature))\n",
    "                range_max = value + int(temperature)\n",
    "                neighbor_params[param_name] = np.random.randint(range_min, range_max + 1)\n",
    "            else:\n",
    "                range_min = max(0.01, value - temperature)\n",
    "                range_max = min(0.99999999999999, value + temperature)\n",
    "                neighbor_params[param_name] = round(np.random.uniform(range_min, range_max), 2)\n",
    "        elif isinstance(value, int):\n",
    "            range_min = max(0, value - int(temperature))\n",
    "            range_max = value + int(temperature)\n",
    "            neighbor_params[param_name] = np.random.randint(range_min, range_max + 1)\n",
    "        else:\n",
    "            range_min = max(0.0, value - temperature)\n",
    "            range_max = min(1.0, value + temperature)\n",
    "            neighbor_params[param_name] = np.random.uniform(range_min, range_max)\n",
    "    return neighbor_params\n",
    "\n",
    "# Function to perform Simulated Annealing optimization\n",
    "def perform_simulated_annealing(X_train, X_test, y_train, y_test, initial_params, max_iterations, initial_temperature, cooling_rate):\n",
    "    current_params = initial_params.copy()\n",
    "    current_classifier = GradientBoostingClassifier(**current_params)\n",
    "    current_classifier.fit(X_train, y_train)\n",
    "    current_pred = current_classifier.predict(X_test)\n",
    "    current_value = calculate_objective_value(y_test, current_pred)\n",
    "\n",
    "    best_params = current_params.copy()\n",
    "    best_value = current_value\n",
    "\n",
    "    for iteration in range(max_iterations):\n",
    "        temperature = initial_temperature / (1 + cooling_rate * iteration)\n",
    "\n",
    "        neighbor_params = generate_neighbor_solution(current_params, temperature)\n",
    "        neighbor_classifier = GradientBoostingClassifier(**neighbor_params)\n",
    "        neighbor_classifier.fit(X_train, y_train)\n",
    "        neighbor_pred = neighbor_classifier.predict(X_test)\n",
    "        neighbor_value = calculate_objective_value(y_test, neighbor_pred)\n",
    "\n",
    "        delta_value = neighbor_value - current_value\n",
    "\n",
    "        if delta_value > 0 or np.exp(delta_value / temperature) > np.random.uniform(0, 1):\n",
    "            current_params = neighbor_params\n",
    "            current_classifier = neighbor_classifier\n",
    "            current_pred = neighbor_pred\n",
    "            current_value = neighbor_value\n",
    "\n",
    "        if neighbor_value > best_value:\n",
    "            best_params = neighbor_params\n",
    "            best_value = neighbor_value\n",
    "\n",
    "    return best_params, best_value\n",
    "\n",
    "\n",
    "# Load the training data from the first CSV file\n",
    "train_data = pd.read_csv(r\"C:\\Users\\KIIT\\Desktop\\Iterations\\iter2\\Combined_6.csv\")\n",
    "\n",
    "# Split the features and target variable\n",
    "X_train = train_data.drop('Facies', axis=1)\n",
    "y_train = train_data['Facies']\n",
    "\n",
    "# Load the test data from the second CSV file\n",
    "test_data = pd.read_csv(r\"C:\\Users\\KIIT\\Desktop\\SB-10.csv\")\n",
    "\n",
    "# Split the features and target variable\n",
    "X_test = test_data.drop('Facies', axis=1)\n",
    "y_test = test_data['Facies']\n",
    "\n",
    "\n",
    "# Define the initial parameters for the gradient boosting classifier\n",
    "initial_params = {\n",
    "    'n_estimators': 100,\n",
    "    'learning_rate': 0.1,\n",
    "    'max_depth': 3,\n",
    "    'min_samples_split': 2,\n",
    "    'min_samples_leaf': 1,\n",
    "    'subsample': 1.0\n",
    "}\n",
    "\n",
    "# Set the parameters for the Simulated Annealing optimization\n",
    "max_iterations = 100\n",
    "initial_temperature = 100.0\n",
    "cooling_rate = 0.01\n",
    "\n",
    "# Perform Simulated Annealing optimization\n",
    "best_params, best_value = perform_simulated_annealing(X_train, X_test, y_train, y_test, initial_params, max_iterations, initial_temperature, cooling_rate)\n",
    "\n",
    "# Print the optimized parameters\n",
    "print(\"Optimized Parameters:\")\n",
    "for param_name, param_value in best_params.items():\n",
    "    print(f\"{param_name}: {param_value}\")\n",
    "\n",
    "# Create a gradient boosting classifier object with the best parameters\n",
    "gb_classifier = GradientBoostingClassifier(**best_params)\n",
    "\n",
    "# Train the classifier\n",
    "gb_classifier.fit(X_train, y_train)\n",
    "\n",
    "# Predict on the test set\n",
    "y_pred = gb_classifier.predict(X_test)\n",
    "\n",
    "# Calculate the accuracy and F1 score of the classifier\n",
    "accuracy = accuracy_score(y_test, y_pred)\n",
    "\n",
    "# Print the best parameters and the performance metrics\n",
    "print(\"Best Parameters:\", best_params)\n",
    "print(\"Best Accuracy:\", best_value)\n",
    "print(\"Accuracy:\", accuracy)"
   ]
  },
  {
   "cell_type": "raw",
   "id": "c5d186d0",
   "metadata": {},
   "source": [
    "Optimized Parameters:\n",
    "n_estimators: 395\n",
    "learning_rate: 0.47740620203029716\n",
    "max_depth: 95\n",
    "min_samples_split: 324\n",
    "min_samples_leaf: 65\n",
    "subsample: 0.6779574271312536\n",
    "Best Parameters: {'n_estimators': 395, 'learning_rate': 0.47740620203029716, 'max_depth': 95, 'min_samples_split': 324, 'min_samples_leaf': 65, 'subsample': 0.6779574271312536}\n",
    "Best Accuracy: 0.903179190751445\n",
    "Accuracy: 0.903179190751445"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "be593daa",
   "metadata": {},
   "source": [
    "Optimized Parameters:\n",
    "n_estimators: 99\n",
    "learning_rate: 0.9370277024799234\n",
    "max_depth: 141\n",
    "min_samples_split: 204\n",
    "min_samples_leaf: 73\n",
    "subsample: 0.8317950544372538\n",
    "Best Parameters: {'n_estimators': 99, 'learning_rate': 0.9370277024799234, 'max_depth': 141, 'min_samples_split': 204, 'min_samples_leaf': 73, 'subsample': 0.8317950544372538}\n",
    "Best Accuracy: 0.9248554913294798\n",
    "Accuracy: 0.7384393063583815"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d8c2d2a6",
   "metadata": {},
   "source": [
    "### randomized search"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "71c5ed48",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:372: FitFailedWarning: \n",
      "65 fits failed out of a total of 500.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.0832308858067883\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.009320402078782\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.0717120953891037\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.0717820827209608\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.0962536997579244\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.0730105547524456\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.0132405525564714\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.0626484146779251\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.0152137276264805\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.033436308079483\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.0025529066795666\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.024643330223596\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.0872761293149444\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_search.py:969: UserWarning: One or more of the test scores are non-finite: [0.6665354  0.95739422 0.95868454 0.94577294        nan 0.54446586\n",
      " 0.95737746        nan 0.67964809 0.56130708 0.92246334 0.91602011\n",
      " 0.94961877 0.95351487 0.79338081 0.62172602        nan 0.53634688\n",
      " 0.57410138 0.5458651  0.94577294 0.91996649 0.93665689 0.95351487\n",
      " 0.47752828        nan 0.7620863  0.6529116  0.94445748 0.70556347\n",
      " 0.61822371 0.7610222  0.80759112 0.52368664 0.76630917        nan\n",
      " 0.64111437 0.57169669 0.94577294 0.20904064 0.41554252 0.9561039\n",
      "        nan 0.6962212  0.54686217 0.76640972 0.52624214 0.43237537\n",
      " 0.56064516 0.50564726 0.50970256        nan 0.83460411 0.41167155\n",
      " 0.61591956 0.82568915 0.66597403 0.65395057        nan        nan\n",
      " 0.77099288 0.68110599 0.82048597 0.95997486 0.33020528        nan\n",
      " 0.8024801  0.29424382 0.96126519 0.49136154 0.34454127 0.77666527\n",
      " 0.58677838 0.79326351        nan 0.54758274 0.94963553 0.29679933\n",
      " 0.95738584 0.75419355 0.72246334 0.69387516 0.96255551 0.51723502\n",
      " 0.70696271 0.95093423 0.35852535        nan 0.46213657 0.57415165\n",
      " 0.73398408 0.6779137  0.76253037 0.95609552 0.52847926        nan\n",
      " 0.71192292 0.95996649 0.51587767 0.6242899 ]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Best Parameters: {'learning_rate': 0.09134878064189968, 'max_depth': 5, 'min_samples_leaf': 6, 'min_samples_split': 9, 'n_estimators': 595, 'subsample': 0.9631385219890038}\n",
      "Accuracy: 0.9205202312138728\n",
      "F1 Score: 0.7889174154899443\n"
     ]
    }
   ],
   "source": [
    "from sklearn.ensemble import GradientBoostingClassifier\n",
    "from sklearn.model_selection import train_test_split, RandomizedSearchCV\n",
    "from sklearn.metrics import accuracy_score, f1_score\n",
    "from scipy.stats import randint, uniform\n",
    "\n",
    "# Load the training data from the first CSV file\n",
    "train_data = pd.read_csv(r\"C:\\Users\\KIIT\\Desktop\\Iterations\\iter2\\Combined_6.csv\")\n",
    "\n",
    "# Split the features and target variable\n",
    "X_train = train_data.drop('Facies', axis=1)\n",
    "y_train = train_data['Facies']\n",
    "\n",
    "# Load the test data from the second CSV file\n",
    "test_data = pd.read_csv(r\"C:\\Users\\KIIT\\Desktop\\SB-10.csv\")\n",
    "\n",
    "# Split the features and target variable\n",
    "X_test = test_data.drop('Facies', axis=1)\n",
    "y_test = test_data['Facies']\n",
    "\n",
    "# Define the parameter distributions for randomized search\n",
    "param_distributions = {\n",
    "    'n_estimators': randint(100, 1000),\n",
    "    'learning_rate': uniform(0.01, 0.999999999999999),\n",
    "    'max_depth': randint(1, 10),\n",
    "    'min_samples_split': randint(2, 20),\n",
    "    'min_samples_leaf': randint(1, 10),\n",
    "    'subsample': uniform(0.1, 1.0)\n",
    "}\n",
    "\n",
    "# Create a gradient boosting classifier object\n",
    "gb_classifier = GradientBoostingClassifier()\n",
    "\n",
    "# Perform randomized search for hyperparameter optimization\n",
    "random_search = RandomizedSearchCV(gb_classifier, param_distributions, n_iter=100, cv=5, scoring='accuracy', random_state=42)\n",
    "random_search.fit(X_train, y_train)\n",
    "\n",
    "# Get the best estimator and its corresponding parameters\n",
    "best_classifier = random_search.best_estimator_\n",
    "best_params = random_search.best_params_\n",
    "\n",
    "# Predict on the test set using the best classifier\n",
    "y_pred = best_classifier.predict(X_test)\n",
    "\n",
    "# Calculate the accuracy and F1 score of the classifier\n",
    "accuracy = accuracy_score(y_test, y_pred)\n",
    "f1 = f1_score(y_test, y_pred, average='macro')\n",
    "\n",
    "# Print the best parameters and the performance metrics\n",
    "print(\"Best Parameters:\", best_params)\n",
    "print(\"Accuracy:\", accuracy)\n",
    "print(\"F1 Score:\", f1)"
   ]
  },
  {
   "cell_type": "raw",
   "id": "49203ea9",
   "metadata": {},
   "source": [
    "Best Parameters: {'learning_rate': 0.1716287140946136, 'max_depth': 6, 'min_samples_leaf': 8, 'min_samples_split': 4, 'n_estimators': 211, 'subsample': 0.2014715428660321}\n",
    "Accuracy: 0.8973988439306358\n",
    "F1 Score: 0.7898192864046523"
   ]
  },
  {
   "cell_type": "raw",
   "id": "16a1aea0",
   "metadata": {},
   "source": [
    "Best Parameters: {'learning_rate': 0.09134878064189968, 'max_depth': 5, 'min_samples_leaf': 6, 'min_samples_split': 9, 'n_estimators': 595, 'subsample': 0.9631385219890038}\n",
    "Accuracy: 0.9205202312138728\n",
    "F1 Score: 0.7889174154899443"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6a4686c6",
   "metadata": {},
   "source": [
    "### grid search"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "58c40f7b",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:372: FitFailedWarning: \n",
      "310 fits failed out of a total of 500.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.2508884729488527\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.5922115592912176\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.5832308858067883\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.0504992519695429\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.4331949117361642\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.3553614103176526\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.0497541333697655\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.1208342600258236\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.186751165663848\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.306857343847617\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.2510770255019446\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.448913824266084\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.0275410183585496\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.139841091301673\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.408120379564417\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.4074401551640625\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.2476901205413622\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.0110370133182314\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.089452760277563\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.11775135052748\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.1414479738275658\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.5962536997579244\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.0856137535862267\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.3209399242521291\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.5730105547524456\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.102637093105192\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.1720041992091832\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.347718773897414\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.1722924691708383\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.0852798742763157\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.1183296523637367\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.3024840839871092\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.4670723185801036\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.1788648955075587\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.369993553098611\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.2601973767177312\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.3300393165618185\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.074173829087325\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.0646738129396114\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.2839637693981412\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.2364035974460112\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.420426843771268\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.2928903586919394\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.4034809303848486\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.1759245752580845\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.3545428740846823\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.5053819764192635\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.0484455219783197\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.3915790437258484\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.026091475046941\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.1133261686923928\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.5076937063485463\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.3050843642966599\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.4227903518766931\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.4685991281894601\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.524643330223596\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.2293986381352626\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.337100705843019\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.2201325978015367\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.053240846828831\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.32571950838836\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 525, in fit\n",
      "    self._check_params()\n",
      "  File \"C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 317, in _check_params\n",
      "    raise ValueError(\"subsample must be in (0,1] but was %r\" % self.subsample)\n",
      "ValueError: subsample must be in (0,1] but was 1.5872761293149444\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "C:\\Users\\KIIT\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_search.py:969: UserWarning: One or more of the test scores are non-finite: [0.72512778        nan        nan 0.41297026        nan        nan\n",
      " 0.95219941        nan        nan        nan        nan        nan\n",
      " 0.53500628        nan        nan 0.53516548 0.91995811        nan\n",
      "        nan 0.95481357        nan        nan        nan        nan\n",
      " 0.96256389 0.84254713 0.95739422 0.58446586        nan        nan\n",
      " 0.80640972 0.95093423 0.39341433 0.92127357        nan        nan\n",
      "        nan 0.92124005 0.30068705 0.9561039         nan 0.76498534\n",
      "        nan        nan        nan        nan        nan        nan\n",
      "        nan 0.74059489        nan        nan        nan 0.35238375\n",
      "        nan 0.73532468        nan 0.95350649 0.72675325 0.431261\n",
      " 0.64093842        nan        nan 0.95609552        nan        nan\n",
      " 0.62155006        nan        nan 0.88766653        nan 0.49189778\n",
      "        nan        nan        nan 0.92770842        nan 0.94963553\n",
      "        nan        nan        nan 0.76994554 0.73790532        nan\n",
      "        nan        nan        nan 0.90936741        nan        nan\n",
      "        nan        nan        nan        nan 0.77287809        nan\n",
      " 0.95092585        nan 0.28005027        nan]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Best Parameters: {'learning_rate': 0.010520376995315819, 'max_depth': 7, 'min_samples_leaf': 9, 'min_samples_split': 4, 'n_estimators': 458, 'subsample': 0.7646558531429417}\n",
      "Accuracy: 0.9205202312138728\n",
      "F1 Score: 0.8207705476819201\n"
     ]
    }
   ],
   "source": [
    "from sklearn.ensemble import GradientBoostingClassifier\n",
    "from sklearn.model_selection import train_test_split, RandomizedSearchCV\n",
    "from sklearn.metrics import accuracy_score, f1_score\n",
    "from scipy.stats import randint, uniform\n",
    "\n",
    "# Load the training data from the first CSV file\n",
    "train_data = pd.read_cs(vr\"C:\\Users\\KIIT\\Desktop\\Iterations\\iter2\\Combined_6.csv\")\n",
    "\n",
    "# Split the features and target variable\n",
    "X_train = train_data.drop('Facies', axis=1)\n",
    "y_train = train_data['Facies']\n",
    "\n",
    "# Load the test data from the second CSV file\n",
    "test_data = pd.read_csv(r\"C:\\Users\\KIIT\\Desktop\\SB-10.csv\")\n",
    "\n",
    "# Split the features and target variable\n",
    "X_test = test_data.drop(''Facies, axis=1)\n",
    "y_test = test_data['Facies']\n",
    "\n",
    "# Define the parameter distributions for random search\n",
    "param_distributions = {\n",
    "    'n_estimators': randint(100, 1000),\n",
    "    'learning_rate': uniform(0.01, 0.999999999999999999999),\n",
    "    'max_depth': randint(3, 10),\n",
    "    'min_samples_split': randint(2, 20),\n",
    "    'min_samples_leaf': randint(1, 10),\n",
    "    'subsample': uniform(0.6, 1.0)\n",
    "}\n",
    "\n",
    "# Create a gradient boosting classifier object\n",
    "gb_classifier = GradientBoostingClassifier()\n",
    "\n",
    "# Perform random search for hyperparameter optimization\n",
    "random_search = RandomizedSearchCV(gb_classifier, param_distributions, n_iter=100, cv=5, scoring='accuracy', random_state=42)\n",
    "random_search.fit(X_train, y_train)\n",
    "\n",
    "# Get the best estimator and its corresponding parameters\n",
    "best_classifier = random_search.best_estimator_\n",
    "best_params = random_search.best_params_\n",
    "\n",
    "# Predict on the test set using the best classifier\n",
    "y_pred = best_classifier.predict(X_test)\n",
    "\n",
    "# Calculate the accuracy and F1 score of the classifier\n",
    "accuracy = accuracy_score(y_test, y_pred)\n",
    "f1 = f1_score(y_test, y_pred, average='macro')\n",
    "\n",
    "# Print the best parameters and the performance metrics\n",
    "print(\"Best Parameters:\", best_params)\n",
    "print(\"Accuracy:\", accuracy)\n",
    "print(\"F1 Score:\", f1)"
   ]
  },
  {
   "cell_type": "raw",
   "id": "afae5320",
   "metadata": {},
   "source": [
    "Best Parameters: {'learning_rate': 0.010520376995315819, 'max_depth': 7, 'min_samples_leaf': 9, 'min_samples_split': 4, 'n_estimators': 458, 'subsample': 0.7646558531429417}\n",
    "Accuracy: 0.9219653179190751\n",
    "F1 Score: 0.8291608374034656"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "571f919d",
   "metadata": {},
   "source": [
    "### bayes search"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "69840d14",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Best Parameters: OrderedDict([('learning_rate', 0.01), ('max_depth', 10), ('min_samples_leaf', 10), ('min_samples_split', 2), ('n_estimators', 100), ('subsample', 0.6)])\n",
      "Accuracy: 0.9219653179190751\n",
      "F1 Score: 0.8286291486291487\n"
     ]
    }
   ],
   "source": [
    "from sklearn.ensemble import GradientBoostingClassifier\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import accuracy_score, f1_score\n",
    "from skopt import BayesSearchCV\n",
    "\n",
    "# Load the training data from the first CSV file\n",
    "train_data = pd.read_csv(r\"C:\\Users\\KIIT\\Desktop\\Iterations\\iter2\\Combined_6.csv\")\n",
    "\n",
    "# Split the features and target variable\n",
    "X_train = train_data.drop('Facies', axis=1)\n",
    "y_train = train_data['Facies']\n",
    "\n",
    "# Load the test data from the second CSV file\n",
    "test_data = pd.read_csv(r\"C:\\Users\\KIIT\\Desktop\\SB-10.csv\")\n",
    "\n",
    "# Split the features and target variable\n",
    "X_test = test_data.drop('Facies', axis=1)\n",
    "y_test = test_data['Facies']\n",
    "\n",
    "# Define the search space for Bayesian optimization\n",
    "param_space = {\n",
    "    'n_estimators': (100, 1000),\n",
    "    'learning_rate': (0.01, 0.9999999999999999, 'log-uniform'),\n",
    "    'max_depth': (3, 10),\n",
    "    'min_samples_split': (2, 20),\n",
    "    'min_samples_leaf': (1, 10),\n",
    "    'subsample': (0.6, 1.0, 'uniform')\n",
    "}\n",
    "\n",
    "# Create a gradient boosting classifier object\n",
    "gb_classifier = GradientBoostingClassifier()\n",
    "\n",
    "# Perform Bayesian optimization for hyperparameter tuning\n",
    "bayes_search = BayesSearchCV(gb_classifier, param_space, n_iter=100, cv=5, scoring='accuracy')\n",
    "bayes_search.fit(X_train, y_train)\n",
    "\n",
    "# Get the best estimator and its corresponding parameters\n",
    "best_classifier = bayes_search.best_estimator_\n",
    "best_params = bayes_search.best_params_\n",
    "\n",
    "# Predict on the test set using the best classifier\n",
    "y_pred = best_classifier.predict(X_test)\n",
    "\n",
    "# Calculate the accuracy and F1 score of the classifier\n",
    "accuracy = accuracy_score(y_test, y_pred)\n",
    "f1 = f1_score(y_test, y_pred, average='macro')\n",
    "\n",
    "# Print the best parameters and the performance metrics\n",
    "print(\"Best Parameters:\", best_params)\n",
    "print(\"Accuracy:\", accuracy)\n",
    "print(\"F1 Score:\", f1)\n"
   ]
  },
  {
   "cell_type": "raw",
   "id": "e5a8d237",
   "metadata": {},
   "source": [
    "Best Parameters: OrderedDict([('learning_rate', 0.01), ('max_depth', 10), ('min_samples_leaf', 10), ('min_samples_split', 2), ('n_estimators', 100), ('subsample', 0.6)])\n",
    "Accuracy: 0.9219653179190751\n",
    "F1 Score: 0.8286291486291487"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
